global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'producer-app'
    static_configs:
      - targets: ['producer-app:5001']

  - job_name: 'consumer-app'
    static_configs:
      - targets: ['consumer-app:5002']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
